### ISSUE TITLE
UWP is supported

### ISSUE THREAD

**Issue by andrewpros** [medokin/soundpad-connector#11]
Just wanted to request for docs update.

UWP is now supported for some time, i did contact the Soundpad creator and the changes was made months ago.

The requirements for ipc to work with UWP apps is to have best at least windows 10 2004, then it is possible to connect from the connector without any workarounds, it could also work before 2004, one or two releases, but it needed to use only specific winapi functions and with 2004 it works out of the box from any code.

**Comment by medokin** [comment]
Thanks for the update, I will update the docs 👍

**Comment by andrewpros** [comment]
One issue for now, it seems its still only available in steam beta channel, not sure about the stand-alone version, already notified creators to update it to stable.

**Comment by medokin** [comment]
Addressed in readme
