### ISSUE TITLE
Support loading a soundlist

### ISSUE THREAD

**Issue by BarRaider** [medokin/soundpad-connector#7]
Currently, there is a SaveSoundlist() function that allows to save a Soundlist. 

Could we also add a LoadSoundList(string fileName) which will load a *.spl file?

**Comment by medokin** [comment]
I can check if soundpad provides such a call, but cannot promise anything. The connector is just a .net wrapper.

**Comment by BarRaider** [comment]
Totally understand, was not able to find actual documentation in the Soundpad website, so figured you may know if that exists of not...

**Comment by medokin** [comment]
It's not supported by rpc. But the implementation of the workaround would be possible with the limitation that you cannot create a new list. Saving a new list would prompt a dialog in soundpad which we cannot handle. Is this an option for you?

**Comment by BarRaider** [comment]
Hi,
So if I understand correctly, it will be possible to open an existing spl file (and play songs) but not modify and save it?

**Comment by medokin** [comment]
You could also modify and save an already **existing** list. Only limitation is that you could not create a new list.

**Comment by BarRaider** [comment]
But if I open an existing spl file, isn't it an already existing list?

**Comment by medokin** [comment]
Ok, another try:

You have a file called myList.spl You do something like LoadSoundList("myList.spl"). Everything would work file. Adding sounds, saving the list.

Soundpad also allows to create a new list like LoadSoundList("fileThatDoesNotExistYes.spl"). Thats something the connector would prevent, because saving this not yet existing file would trigger a prompt.

**Comment by BarRaider** [comment]
Now I got it, sorry for being a little slow!
Yes, that's totally fine. I'm fine with only *existing* files.

**Comment by BarRaider** [comment]
Is this something you think you'll be able to add sometime soon?

**Comment by medokin** [comment]
Nuget package is indexing and should be available shortly
