### ISSUE TITLE
Index returned in GetSoundList function does not match actual index in SoundPad

### ISSUE THREAD

**Issue by BarRaider** [medokin/soundpad-connector#9]
GetSoundList() returns a list of sounds and an index for each.
The index shown in the list does not match the actual index shown in the UI.
![Soundpad](https://user-images.githubusercontent.com/46548278/58392218-d344f800-7fed-11e9-8255-6ac275f09eb8.png)

**Comment by medokin** [comment]
This seems to an issue due to categories. Thanks for reporting.

**Comment by medokin** [comment]
Well it's not an issue rather than a missing implementation of categories in soundpads rpc.
The index from GetSoundList is not category scoped. So if you use categories,  it may be different inside the GUI. PlaySound() will play the sound by the index from GetSoundList().
